# Generated by Django 5.2.8 on 2025-11-13 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('tanggal_registrasi', models.DateTimeField(auto_now_add=True)),
                ('tanggal_lahir', models.DateField(default=django.utils.timezone.now)),
                ('jenis_kelamin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_pengaduan', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warga.warga')),
            ],
        ),
    ]
