# Generated by Django 5.2.4 on 2025-11-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warga',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='nik',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='no_telepon',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='tanggal_registrasi',
        ),
        migrations.AlterField(
            model_name='warga',
            name='nama_lengkap',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warga',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
